asset_path: /home/zzh/workspace/surgical_robot_project/assets/models/urdf/omni.urdf
usd_dir: /home/zzh/workspace/surgical_robot_project/assets/models/usd
usd_file_name: null
force_usd_conversion: false
make_instanceable: true
fix_base: true
root_link_name: base
link_density: 0.0
merge_fixed_joints: true
convert_mimic_joints_to_normal_joints: false
joint_drive:
  drive_type: acceleration
  target_type: position
  gains:
    stiffness:
      waist: 1
      shoulder: 1
      elbow: 1
      yaw: 10000
      pitch: 10000
      roll: 10000
    damping:
      waist: 0.1
      shoulder: 0.1
      elbow: 0.1
      yaw: 1000
      pitch: 1000
      roll: 1000
collider_type: convex_hull
self_collision: false
replace_cylinders_with_capsules: false
collision_from_visuals: false
func: isaaclab.sim.spawners.from_files.from_files:spawn_from_urdf
visible: true
semantic_tags: null
copy_from_source: true
mass_props:
  mass: 0
  density: null
deformable_props: null
rigid_props:
  rigid_body_enabled: null
  kinematic_enabled: null
  disable_gravity: true
  linear_damping: null
  angular_damping: null
  max_linear_velocity: null
  max_angular_velocity: null
  max_depenetration_velocity: null
  max_contact_impulse: null
  enable_gyroscopic_forces: null
  retain_accelerations: null
  solver_position_iteration_count: null
  solver_velocity_iteration_count: null
  sleep_threshold: null
  stabilization_threshold: null
collision_props: null
activate_contact_sensors: false
scale: !!python/tuple
- 1
- 1
- 1
articulation_props:
  articulation_enabled: null
  enabled_self_collisions: false
  solver_position_iteration_count: 100
  solver_velocity_iteration_count: 100
  sleep_threshold: 0.01
  stabilization_threshold: 0.01
  fix_root_link: true
fixed_tendons_props: null
joint_drive_props: null
visual_material_path: material
visual_material: null
##
# Generated by UrdfConverter on 2025-07-24 at 15:30:06.
##
